 main: eu.reborn_minecraft.zhorse.ZHorse
 name: ZHorse
 version: 1.6.1
 depend: [Vault]
 description: This plugin provides an enhanced management of horses
 author: Z3dd7

 commands:
   zhorse:
      description: Main ZHorse command
      usage: /<command> [arguments]
      aliases: [zh]
      
 permissions:
    zh.*:
        description: Grants full access to ZHorse
        children:
            zh.*.admin: true
            zh.*.free: true
            zh.admin.*: true
            zh.reload: true
            zh.spawn: true
            zh.tame: true
            zh.use: true

    zh.use:
        description: Grants access to all player commands
        children:
            zh.carry: true
            zh.claim: true
            zh.give: true
            zh.free: true
            zh.friend.*: true
            zh.heal: true
            zh.info: true
            zh.kill: true
            zh.help: true
            zh.here: true
            zh.list: true
            zh.lock: true
            zh.protect: true
            zh.rename: true
            zh.settings.*: true
            zh.share: true
            zh.tp: true
            
    zh.admin.* :
        description: Grants access to all admin subcommands
        children:
            zh.admin: true
            zh.admin.clear: true
            zh.admin.import: true

    zh.friend.* :
        description: Grants access to all friend subcommands
        children:
            zh.friend: true
            zh.friend.add: true
            zh.friend.list: true
            zh.friend.remove: true
            
    zh.settings.* :
        description: Grants access to all settings subcommands
        children:
            zh.settings: true
            zh.settings.favorite: true
            zh.settings.language: true
        
    zh.*.admin:
        description: Grants admin access to all commands
        children:
            zh.admin.admin: true
            zh.carry.admin: true
            zh.claim.admin: true
            zh.free.admin: true
            zh.friend.admin: true
            zh.give.admin: true
            zh.heal.admin: true
            zh.help.admin: true
            zh.here.admin: true
            zh.info.admin: true
            zh.kill.admin: true
            zh.list.admin: true
            zh.lock.admin: true
            zh.protect.admin: true
            zh.reload.admin: true
            zh.rename.admin: true
            zh.settings.admin: true
            zh.share.admin: true
            zh.spawn.admin: true
            zh.tame.admin: true
            zh.tp.admin: true
            
    zh.*.free :
        description: Grants free access to all commands
        children:
            zh.admin.free: true
            zh.admin.free: true
            zh.claim.free: true
            zh.free.free: true
            zh.friend.free: true
            zh.give.free: true
            zh.heal.free: true
            zh.help.free: true
            zh.here.free: true
            zh.info.free: true
            zh.kill.free: true
            zh.list.free: true
            zh.lock.free: true
            zh.protect.free: true
            zh.reload.free: true
            zh.rename.free: true
            zh.settings.free: true
            zh.share.free: true
            zh.spawn.free: true
            zh.tame.free: true
            zh.tp.free: true